sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t hjhj97/docker-react-app -f ./docker-react-app/Dockerfile.dev ./docker-react-app

script:
  - docker run -e CI=true hjhj97/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"
